bootstrap_servers: okr_kafka:9092
topic: ai-data
group_id: ai-consumer

# Producer configuration
producer_config:
  retries: 5
  linger_ms: 10
  batch_size: 16384
  buffer_memory: 33554432

# Consumer configuration
consumer_config:
  auto_offset_reset: earliest
  enable_auto_commit: true
  auto_commit_interval_ms: 1000
  session_timeout_ms: 30000
