name: Branch Protection and Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop, test]

jobs:
  # Code Quality Checks
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pylint pytest pytest-cov
      
      - name: Run code formatting check
        run: |
          echo "Checking code formatting..."
          black --check --diff . || echo "Code formatting issues found - will be fixed in separate PR"
      
      - name: Run linting
        run: |
          echo "Running linting checks..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          # Run pytest and generate coverage if possible. Handle 'no tests collected' (exit code 5).
          set +e
          python -m pytest -v --maxfail=1 --disable-warnings --cov=src --cov-report=xml
          exitcode=$?
          set -e
          if [ $exitcode -eq 5 ]; then
            echo "No tests collected; skipping unit tests."
            exit 0
          else
            exit $exitcode
          fi
      
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  # Security Scan
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json || true
      
      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: bandit-report.json

  # Docker Build Test
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker images
        run: |
          docker build -t okr-api:test -f apps/api/Dockerfile .
          echo "Skipping kafka producer/consumer images: not present in this repository"
      
      - name: Test Docker Compose
        run: |
          docker compose -f docker-compose.yml config

  # ETL Pipeline Validation
  etl-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml numpy pandas kafka-python confluent-kafka
      
      - name: Validate Airflow DAGs (static syntax)
        run: |
          echo "Validating Airflow DAG Python syntax..."
          python - << 'PYCODE'
import os, sys, ast, glob
folder = 'src/dags'
errors = []
for path in glob.glob(os.path.join(folder, '*.py')):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            ast.parse(f.read(), filename=path)
        print(f"✓ Syntax OK: {path}")
    except Exception as e:
        print(f"❌ Syntax error in {path}: {e}")
        errors.append((path, str(e)))
if errors:
    sys.exit(1)
print('All DAG files passed static syntax check')
PYCODE
      
      - name: Validate ETL Pipeline Components
        run: |
          echo "Validating ETL pipeline components (non-Airflow modules)..."
          python - << 'PYCODE'
import sys
sys.path.append('src')
try:
    import utils.helpers  # noqa: F401
    import data.streaming  # noqa: F401
    print('Core ETL utility modules imported successfully')
except Exception as e:
    print('Core ETL module import failed:', e)
    raise
PYCODE
      
      - name: Validate Configuration Files
        run: |
          echo "Validating configuration files..."
          python -c "
          import yaml
          import os
          
          config_files = [
              'configs/db_config.yaml',
              'configs/kafka_config.yaml',
              'configs/model_config.yaml'
          ]
          
          for config_file in config_files:
              if os.path.exists(config_file):
                  try:
                      with open(config_file, 'r') as f:
                          yaml.safe_load(f)
                      print(f'✓ {config_file} is valid YAML')
                  except Exception as e:
                      print(f'❌ {config_file} has invalid YAML: {e}')
                      exit(1)
              else:
                  print(f'⚠ {config_file} not found')
          "

  # Deployment Validation (Oracle Only)
  deployment-validation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Oracle Deployment Configuration
        run: |
          echo "Validating Oracle deployment configuration..."
          
          # Check if Oracle-specific files exist
          required_files=(
              "deploy/oracle-setup.sh"
              "deploy/mlapi.service"
              "deploy/nginx/mlapi.conf"
          )
          
          for file_path in "${required_files[@]}"; do
              if [ ! -f "$file_path" ]; then
                  echo "Missing required deployment file: $file_path"
                  exit 1
              fi
              echo "✓ $file_path found"
          done
          
          # Validate service configuration
          if [ -f "deploy/mlapi.service" ]; then
              echo "✓ systemd service configuration found"
          fi
          
          echo "Oracle deployment configuration validated"
      
      - name: Check Oracle Secrets
        run: |
          if [ -n "${{ secrets.ORACLE_SSH_KEY }}" ]; then
              echo "✓ Oracle SSH key configured"
          else
              echo "⚠ Oracle SSH key not configured - deployment will be skipped"
          fi
