name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint only
        run: |
          python -m pip install flake8
          flake8 || true
      - name: Build Docker images (compat paths)
        run: |
          docker build -t okr-api:test -f api/Dockerfile .
          docker build -t okr-producer:test -f kafka_pipeline/producers/Dockerfile .
          docker build -t okr-consumer:test -f kafka_pipeline/consumers/Dockerfile .
      - name: Validate ETL pipeline components
        run: |
          echo "Validating ETL pipeline components..."
          python scripts/validate_etl_pipeline.py
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          python -m pip install pytest pytest-cov
          pytest -q

