name: Deploy to Oracle Server

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-oracle
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=yes ${SERVER_USER}@${SERVER_HOST} '
            set -euo pipefail
            cd ~/okr-project
            git pull --rebase --autostash
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d
            docker compose ps
          '
