name: deploy-only
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      # Step 1: Setup SSH key and verify host identity
      - name: Setup SSH Key and Verify Host
        if: ${{ secrets.ORACLE_SSH_KEY != '' }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/oracle.key
          chmod 600 ~/.ssh/oracle.key
          ssh-keyscan -H 139.185.33.139 >> ~/.ssh/known_hosts

      # Step 2: Test SSH connection
      - name: Test SSH Connection
        if: ${{ secrets.ORACLE_SSH_KEY != '' }}
        run: |
          ssh -i ~/.ssh/oracle.key ubuntu@139.185.33.139 "echo 'SSH connection successful'; uname -a"

      # Step 3: Install rsync
      - name: Install rsync on runner
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y rsync -qq

      # Step 4: Deploy code via rsync
      - name: Deploy Code to Server
        if: ${{ secrets.ORACLE_SSH_KEY != '' }}
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/oracle.key" ./ ubuntu@139.185.33.139:/home/ubuntu/okr-project/

      # Step 5: Restart API container
      - name: Restart API Container
        if: ${{ secrets.ORACLE_SSH_KEY != '' }}
        run: |
          ssh -i ~/.ssh/oracle.key ubuntu@139.185.33.139 << 'EOF'
          echo "Restarting API container..."
          docker-compose -f ~/okr-project/docker-compose.yml restart api
          echo "API container restarted successfully!"
          EOF